language: python
python:
  - "2.7"
env:
- sshmux_test_host=127.0.0.1
- sshmux_test_user=ubuntu
- sshmux_test_key=~/.ssh/id_rsa
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install -e .
before_script:
  # Allow us to SSH passwordless to localhost
  - ssh-keygen -f ~/.ssh/id_rsa -N ""
  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
  - eval $(ssh-agent)
  - ssh-add
script:
  - flake8 sshmux/.
  #  - python tests/test_ssh.py -v
